# LumConfigVersion.cmake - version information for Lum
set(PACKAGE_VERSION "0.1.2")

if(PACKAGE_FIND_VERSION VERSION_LESS PACKAGE_VERSION)
    set(PACKAGE_VERSION_COMPATIBLE FALSE)
else()
    set(PACKAGE_VERSION_COMPATIBLE TRUE)
endif()

set(PACKAGE_VERSION_EXACT ${PACKAGE_FIND_VERSION_EXACT})
