name: Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Export GitHub Actions cache environment variables
        uses: actions/github-script@v7
        with:
          script: |
            core.exportVariable('ACTIONS_CACHE_URL', process.env.ACTIONS_CACHE_URL || '');
            core.exportVariable('ACTIONS_RUNTIME_TOKEN', process.env.ACTIONS_RUNTIME_TOKEN || '');
      
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up vcpkg
        uses: microsoft/vcpkg-action@v10

      - name: Install dependencies
        run: ./vcpkg install
        env: 
          VCPKG_BINARY_SOURCES: "clear;x-gha,readwrite"
          
      - name: Build the project
        run: make
