name: Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: vcpkg-action
        uses: johnwason/vcpkg-action@v6                  
          
      - name: Checkout code
        uses: actions/checkout@v3

      - name: run-vcpkg
        uses: lukka/run-vcpkg@v7.6

      - name: Install dependencies
        run: vcpkg install
        # env: 
        #   VCPKG_BINARY_SOURCES: "clear;x-gha,readwrite"
          
      - name: Build the project
        run: make
