name: Build with Linux Clang

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build-linux-clang:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: Install Clang
      run: sudo apt-get update && sudo apt-get install -y clang

    - name: Cache CMake and Build Files
      uses: actions/cache@v3
      with:
        path: |
          ~/.cmake/packages
          build
        key: clang-${{ github.ref }}-${{ github.sha }}
        restore-keys: |
          clang-${{ github.ref }}

    - name: Configure CMake
      run: >
        cmake -B build
        -DCMAKE_CXX_COMPILER=clang++
        -DCMAKE_C_COMPILER=clang
        -DCMAKE_BUILD_TYPE=Release
        -S .

    - name: Build
      run: cmake --build build --config Release

    - name: Run Tests
      working-directory: build
      run: ctest --output-on-failure
