name: Build with Windows MinGW (MSYS2)

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build-windows-mingw:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: Install MSYS2
      uses: msys2/setup-msys2@v2
      with:
        msystem: mingw64
        install: mingw-w64-x86_64-gcc mingw-w64-x86_64-cmake mingw-w64-x86_64-make

    - name: Cache CMake and Build Files
      uses: actions/cache@v3
      with:
        path: |
          ~/.cmake/packages
          build
        key: mingw-${{ github.ref }}-${{ github.sha }}
        restore-keys: |
          mingw-${{ github.ref }}

    - name: Configure CMake
      shell: msys2 {0}
      run: >
        cmake -B build
        -G "MinGW Makefiles"
        -DCMAKE_CXX_COMPILER=g++
        -DCMAKE_C_COMPILER=gcc
        -DCMAKE_BUILD_TYPE=Release
        -S .

    - name: Build
      shell: msys2 {0}
      run: cmake --build build --config Release

    - name: Run Tests
      shell: msys2 {0}
      working-directory: build
      run: ctest --output-on-failure
